### ISSUE TITLE
Feature request : Option to set HTTPS proxy parametters to proxy IBM Cloud public API endpoints

### ISSUE THREAD

**Issue by captnbp** [ibm-cloud-security/vault-plugin-secrets-ibmcloud#11]
We are a dedicated MZR account in an air-gaped environment. The only way to reach IBM public endpoints is to use the corporate proxy.

We could set the global proxy parameters for the whole Vault instance, but it would affect all other internal https endpoints. We don't want this.

It would be great to specify the proxy parameters in this command: `vault write ibmcloud/config api_key=<adminAPIKey> account_id=<accountID> proxy_url=http://<optional user>:<optional pass>@<proxy url>:<proxy port>`

This proxy parameter would only be used for IBM Cloud public endpoints.

**Comment by captnbp** [comment]
https://github.com/ibm-cloud-security/vault-plugin-auth-ibmcloud/issues/7

**Comment by smatzek** [comment]
While it is not specifically "proxy" support, the support for private IAM endpoints was just delivered under #17. Depending on the configuration of your proxy this support, which allows the specification of the IAM endpoint to use could functionally work for your case.

Since there are no current plans to deliver proxy support now that private endpoint support is delivered I am closing this issue.

**Comment by smatzek** [comment]
@captnbp The private endpoint support does not work for some HTTP proxies as noted in #22. I have created PR #23 to address this.
